spring.application.name=backend


spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/Autofinanzas
spring.datasource.username=postgres
spring.datasource.password=12345678

ip.frontend=http://localhost:4200
jwt.secret=6PHHIf8dJmQxw2m7Qb1x5Q8fJjvY8e2e0t6h9g4Qv1M5y7L3c2r8N1s6W4X9A0B=